### ISSUE TITLE
Category field empty

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/delanyandlong#1]
For example `"itemNumber": "DL8001-30"`. It's a leather but no category is set. How do they suggest we organize the different items into groups?

I assume it is leather since `name": "Outdoor Leather"`.

**Comment by webmasterkai** [comment]
I could look in `"descriptions"` for the `"OUTDOOR LEATHER"` value.

**Comment by webmasterkai** [comment]
Sometimes it looks to be in the `itemNumber`. I think `DLT201-29` is a trim, the `T` part there.

**Comment by webmasterkai** [comment]
No `comments`,`content`,`design`, `itemComments `, `primaryColor` or `secondaryColor` values for us to build information from. I don't think there is "name" information.

**Comment by webmasterkai** [comment]
I think these fields could be used to populate other search information if they so desire. I think @bjornmeansbear was asking about this at one point? That we'd need to tell them what to look for or ask PDF Systems or something...

**Comment by bjornmeansbear** [comment]
Yeah, that's the one thing from #2 that we don't have — the "Name" — that shows on specs page... It's something we can ask them about when we look over the pricelist with them?

**Comment by webmasterkai** [comment]
The name that shows on the specs page is just the color I think.

**Comment by bjornmeansbear** [comment]
`name` on specifications page is the name of that fabric, for example: http://delanyandlong.com/byName.cfm?CID=03&FID=DL10001 — those are all the "Dhow" line, and then it comes in sand, whitecap, etc. http://delanyandlong.com/byName.cfm?CID=03&FID=DL1001 is the Commodore family, etc.

Can we add name to the pricelist, etc.? (related to #22)

**Comment by webmasterkai** [comment]
Can you find it in the data somewhere? I don't see somethings like `patternName` or `name` that would contain that info. If it shows up in the data, we can do something.

**Comment by bjornmeansbear** [comment]
How do I look at the direct from Ordertrack stuff?

**Comment by bjornmeansbear** [comment]
So I think we've resolved this? Other than the name and color and the few other things we've brought in, Esteban, the main contact at DL, says they aren't using any of the other special fields that RG might have been since they have less stuff and less needs for specialty categories, etc.
