### ISSUE TITLE
Zip code field only allowing numbers, not the country information.

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#101]
This is a problem for international clients — CANADA, etc. need to be able to be entered

**Comment by bjornmeansbear** [comment]
Should I get some customer# and country entries from them to test?

**Comment by bjornmeansbear** [comment]
Here's an example: 
2. International accounts being able to log-in .... I have one example..ACC # 028689 ... they are located in France. Still says that you need a numeric # to log in.

028689 / France (or does it need to be FRANCE)

**Comment by webmasterkai** [comment]
It would be best to have a list of approved countries but we can also just turn off validation.

**Comment by webmasterkai** [comment]
Way more difficult and hacky than I thought.
