### ISSUE TITLE
D&L concerned that logged in session is so easy to disrupt by page refresh, etc.

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#104]

**Comment by bjornmeansbear** [comment]
is this related to #80?

**Comment by bjornmeansbear** [comment]
Is this really closed? If I hit refresh on my local I'm not remembered at all and my favorites appear to be lost when I log back in as a trade person.

**Comment by webmasterkai** [comment]
saving favs to firebase is different from session handling
