### ISSUE TITLE
Update images on BackBlaze w/ new sarah images

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#105]
I re uploaded 
DLT102-01 Sand
DLT102-05 Bluebird
DLT102-06 Sky
DLT102-07 Mist
DLT102-09 Olive
DLT102-13 Ebony

And it looks like DLT104-05 Bluebird was mislabeled, which I changed on dropbox.

**Comment by bjornmeansbear** [comment]
okay, added these to backblaze. Waiting for them to show up on imigix...

**Comment by webmasterkai** [comment]
1month cache

**Comment by bjornmeansbear** [comment]
all the DLT102s were missing/404s, does that get cached?

**Comment by webmasterkai** [comment]
5min on 404

**Comment by bjornmeansbear** [comment]
cool, well, I'll check em tomorrow then... try to wrap up something else tonight.

**Comment by webmasterkai** [comment]
source: https://f001.backblazeb2.com/file/delanyandlong/DLT102-01.jpg
cloudflare: https://b2.cape.io/file/delanyandlong/DLT102-01.jpg
imgix: https://delanyandlong.imgix.net/DLT102-01.jpg

**Comment by bjornmeansbear** [comment]
Still not showing up, should I try purging them w/ the imgix tool?
