### ISSUE TITLE
Clicking another [+] add to fav/projects button should close an open favorite container popup

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#106]
We don't want this to happen to everyone:
![screenshot 2016-10-18 14 07 08](https://cloud.githubusercontent.com/assets/324987/19490206/4a9bdc4c-953c-11e6-8fbb-7d0680b4fb92.png)

**Comment by webmasterkai** [comment]
Fixed with `cape-redux-collection@1.1.0`.
