### ISSUE TITLE
Add text disclaimer to detail page

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#108]
include the "Colors and scale shown are not exact. Please request actual samples from your DeLany & Long distributor." wording when they are looking at the fabric in detail?

Maybe add this to bottom of pricelist/collection views too?

**Comment by bjornmeansbear** [comment]
I got this setup. Its unclear to me how to get data I add to the defaultState.js file to show up other places...

**Comment by webmasterkai** [comment]
Data deciding happens in the container. `container/Detail.js` has an import that is used as `mapStateToProps`.
`import { itemDetailSelector as mapStateToProps } from '../redux/select/item'`
open redux/select/item.js and look for `itemDetailSelector`.

You'd need to create a selector that pulls the thing you want from the master state object. Check commit

**Comment by bjornmeansbear** [comment]
Thanks @webmasterkai
