### ISSUE TITLE
Create additional lists when logged in/authenticate

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#111]
they have a favs project just like anon does

The anon list must be able to transfer to an auth account
- [x] Popup window when auth user clicks [+] button.
- [x] Add to collection when clicking collection title string within list on overview popup.
- [x] Mark if already in collection.
- [x] Allow removal from collection by clicking.
- [x] Ability to create new (project) collection list.

**Comment by webmasterkai** [comment]
Duplicate. Use #69 instead.

**Comment by bjornmeansbear** [comment]
Is this also related to issues #70, #71, #72, and #76?
