### ISSUE TITLE
ability to view other collections

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#115]

**Comment by bjornmeansbear** [comment]
On Rogers & goffigon the projects/collections are just a list of the lists, should we just make that part of "favorites" ??? Add a new "section" w/ title for each new collection just running down that page?

**Comment by bjornmeansbear** [comment]
![screenshot 2016-11-02 23 00 49](https://cloud.githubusercontent.com/assets/324987/19954674/671488ae-a150-11e6-909b-db9dcca89ea3.png)

is this basic/simple enough? we can add complexity like rearranging or open/closing if necessary, but lets just start w/ that?

**Comment by bjornmeansbear** [comment]
shoot, that's maybe a different issue? do we need a single page view for each collection for "sharing" purposes? should that be the place to start?

**Comment by webmasterkai** [comment]
Added "view" link in popup that directs to the project specific page. I can create an index page that has all the projects next.

**Comment by bjornmeansbear** [comment]
Awesome!
