### ISSUE TITLE
Do `position` and `notes` in the favorites popup actually save to the DB?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#120]
They seem to be perpetually stuck on `saving` if I try to edit them.

![screenshot 2016-11-04 23 39 58](https://cloud.githubusercontent.com/assets/324987/20027350/25324b12-a2e8-11e6-89ac-d56589d9be46.png)

**Comment by webmasterkai** [comment]
Saving notes. Big performance issues on input.

**Comment by bjornmeansbear** [comment]
Okay, that's a start! A really long note might need a style tweak... but I think things are pretty good.
