### ISSUE TITLE
Add functionality to mobile menu

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#13]
Menu is designed. Button to trigger show/hide of skinny nav is there, just need to enable the  functionality.

**Comment by webmasterkai** [comment]
Where do we define `isSkinny` conditions?

**Comment by bjornmeansbear** [comment]
shoot, I did not define it anywhere.
Currently using 800px (50em) as the main break in my CSS
skinny <= 800px, wide > 800px

**Comment by bjornmeansbear** [comment]
woah... I tried to sort out how maybe to make the menu button do things... I was unable to sort it out... but I think I was close... it just broke a bunch of other things so I put it all back.
c6c553c41f4fce7b2164e26250d4e0bc408d55be

**Comment by bjornmeansbear** [comment]
okay, I think the current solution is good and negates this.
