### ISSUE TITLE
Homepage Random Selection now includes items w/out images

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#133]
Can we get it to go back to only items w/ images there please?

**Comment by webmasterkai** [comment]
That will have to be ported to firebase.

**Comment by webmasterkai** [comment]
There is no easy way for the browser to know if the image is missing because there is a default image set at imgix. No image error is thrown because an image is always returned from server, even if 404.

**Comment by bjornmeansbear** [comment]
Well shoot. Okay, so I'll delete the default image. And then we'll just need to figure out what to do on the pricelist?

Kristian Bjørnard
507-301-8402
@bjornmeansbear

Please pardon brevity and mistakes

**Comment by bjornmeansbear** [comment]
I deleted the missing image from imgix. So they'll for real be missing now. Um, and I guess lets hide it on the homepage, but for now they can still show up elsewhere...  I'll double confirm with them what they want to happen elsewhere.

**Comment by bjornmeansbear** [comment]
This is solved?

**Comment by bjornmeansbear** [comment]
> The best thing would be to get the list from b2 on the backend so we don't rely on user browsers to tell us what's missing

**Comment by webmasterkai** [comment]
Ran a script that tells firebase what items have images. The script will need to be run every time images on B2 are updated.
