### ISSUE TITLE
What other "Views" are needed on the pricelist?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#17]
If we basically turn the structure of the pricelist into the container for all the different textile views, what are we missing in the selection menu?
- 3-up?
- Anything else?

**Comment by webmasterkai** [comment]
Homepage, Favs, Projects are filters not display modes so they will need to move somewhere else.

**Comment by webmasterkai** [comment]
Well, homepage is a filter and a display mode perhaps?
