### ISSUE TITLE
Do we want to recreate the "Specifications" page?

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/delanyandlong#2]
http://delanyandlong.com/specifications.cfm

I imagine the pricelist basically takes care of this

**Comment by bjornmeansbear** [comment]
I can ask, but yeah, I think this is basically the pricelist

**Comment by bjornmeansbear** [comment]
I think that the `Fabric` column on http://delanyandlong.com/specifications.cfm corresponds to the `name` of a the whole family, `color` is specific to each item (for example, BREAKER describes all of these http://delanyandlong.com/byName.cfm?CID=17&FID=DL1007) — but you're saying we can't see `name` or `fabruc` data in what comes from order track?

**Comment by bjornmeansbear** [comment]
If we have "name" in addition to color now, then there is nothing else missing from the specs page that we have on pricelist.

**Comment by webmasterkai** [comment]
I was thinking more a fabric only view that didn't have individual color rows.

**Comment by bjornmeansbear** [comment]
Ah! I thought you just meant, was there content there that we needed for what we were building.
So, we could do that as an option in our dropdown of views then? It would be potentially nice as a higher level view.
