### ISSUE TITLE
Need close/back button on detail view

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#20]

**Comment by bjornmeansbear** [comment]
button is there, just needs to close the detail and:
a) if you went from something take you back to where you were,
b) if you were sent a detail link directly (so don't have a "back"), then it takes you to the collection page.
anything else that needs figuring out for how this button should work?

**Comment by webmasterkai** [comment]
Look through the browser history in reverse chronological order. Find first instance of non-detail page. Send user back to that page. If no non-detail page is found send to /collection.

**Comment by bjornmeansbear** [comment]
Yes! I love it.

**Comment by bjornmeansbear** [comment]
This seems to be working now.
