### ISSUE TITLE
Add Name column to pricelist.

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#22]
Between item# and img thumbnail.
Should only show on 1st row like the first part of the item#

related to #1

**Comment by bjornmeansbear** [comment]
I added the couple lines to defaultState.js, but maybe that `name` field is actually empty from ordertrack? or we didn't yet include it?

**Comment by webmasterkai** [comment]
empty

**Comment by bjornmeansbear** [comment]
So, now that this is sorted from the data, I think we can get this on there right?

**Comment by webmasterkai** [comment]
It's in there now.

**Comment by bjornmeansbear** [comment]
Thanks!

**Comment by webmasterkai** [comment]
This is done right?

**Comment by bjornmeansbear** [comment]
Yeah, weird, I thought we closed this.
