### ISSUE TITLE
We need a way to select the images that appear on the homepage.

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#23]

**Comment by webmasterkai** [comment]
Have any suggestions? I think we just do a specific "project" list.

**Comment by bjornmeansbear** [comment]
Oh yeah! that's great

**Comment by webmasterkai** [comment]
Should the front page be limited to one color per fabric style or just allow whatever they decide?

**Comment by bjornmeansbear** [comment]
Whatever they decide. It is unlikely that they'd select multiple items from the same parent style, but we should allow for it

**Comment by bjornmeansbear** [comment]
related to #28 ?
