### ISSUE TITLE
Include whether or not something is a Textile, Passementerie, Leather, or SummerSale item in its row

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#27]
I'd like to icon/mark them in some way for easy browsing.

**Comment by bjornmeansbear** [comment]
Also! Drapery/Window treatment... learning from PDF systems if they can include this in ordertrack data for us...

**Comment by bjornmeansbear** [comment]
so I got this started... it will need a better solution, where maybe its just the first letter or something so I can do my styled (T) or (L) etc., but I'm learning!

**Comment by webmasterkai** [comment]
SummerSale isn't a category. An item always has a category value but doesn't always have a discontinued attribute. Should `SS` overwrite the category value?

**Comment by bjornmeansbear** [comment]
No. Good point — I guess its would be a textile still AND have some other signifier that it was a summerSale item.
