### ISSUE TITLE
I need help figuring out how to make buttons do things in the React components

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#29]
I know how to choose a button and declare its behaviors and targets w/ javascript/jquery, but I don't understand how that is sorted in our new setup. Please show me an example @webmasterkai !

**Comment by webmasterkai** [comment]
If you have a short list of other features you want I can see if anything is easy to demonstrate.

**Comment by bjornmeansbear** [comment]
I see that you made the related colors one work... I was going to try and do the menu button in skinny mode. But you can make that work if you are looking for things to do.

**Comment by webmasterkai** [comment]
Menu button in skinny mode is #13?

**Comment by bjornmeansbear** [comment]
yep
