### ISSUE TITLE
On Pricelist trying to type in an item number does not seem to return any results

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#3]
I think that should be something a user can search by too...

![screenshot 2016-06-20 13 29 46](https://cloud.githubusercontent.com/assets/324987/16204054/1607c5cc-36eb-11e6-9499-bdda4eb22b2c.png)

![screenshot 2016-06-20 13 30 19](https://cloud.githubusercontent.com/assets/324987/16204084/2bf9a1f2-36eb-11e6-8571-52685482f147.png)

![screenshot 2016-06-20 13 30 25](https://cloud.githubusercontent.com/assets/324987/16204083/2bf7b220-36eb-11e6-9015-b3bfe80b210b.png)

**Comment by webmasterkai** [comment]
Oh, good call!
