### ISSUE TITLE
Calculate height of the textile tiles so that menu can be vertically centered...

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#32]
Using flexbox, I just need to give the container of the menu a height on the homepage and it will do the rest... I know how to easily request the height from one thing and assign it to another w/ ~~vanilla javascript~~ jquery, but its not clear to me how to do it in our current setup within the component — maybe because the elements that need to match are from two different components?

![screenshot 2016-08-02 11 33 38](https://cloud.githubusercontent.com/assets/324987/17334752/6348af3c-58a5-11e6-8243-360ce857e218.png)

**Comment by webmasterkai** [comment]
We've done something like this before. Can you help me remember what project? Something about taking measurements when the screen size changes.

**Comment by bjornmeansbear** [comment]
I think it was on the deutsch site maybe? I made some goofy buttons that needed to figure out how tall to be based on the images in the slideshow perhaps?

**Comment by webmasterkai** [comment]
Yeah that sounds familiar. I'll take a look. The bummer is that the page needs to render first before the menu will resize.

**Comment by bjornmeansbear** [comment]
Well, I can come up with another way... I had a CSS idea while I was pondering this the other day.
I can try to implement that first before we wander down this rabbit hole code wise, maybe focus on some other features first?

**Comment by webmasterkai** [comment]
On RWDF we did a single size check when the component mounts but I don't see anything that listens to page resizes.

**Comment by bjornmeansbear** [comment]
Okay.
Well, let me try my CSS idea. Then we can come back to sorting it out in the app if that doesn't work.
