### ISSUE TITLE
Color filters

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#35]
Delany and Long uses standard color names for all the different textiles. They desire a color filter, but it just needs to include the color terms as they are assigned directly to each textile in the color field... does that make sense?

**Comment by webmasterkai** [comment]
Looks like about 50 different colors.

**Comment by bjornmeansbear** [comment]
something like shade/robin is really shade AND robin, not a new color — too much work to deal with that?

**Comment by webmasterkai** [comment]
Made `color` an array and now call it `colors`. The old `color` field is calculated on the client. Searching checks the array of possible colors for a match.
http://order-track.cape.io/items/parse/dl
