### ISSUE TITLE
Where does summer sale go?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#41]
Is it an option in a dropdown? do we make it a button like Textile, Passementerie, etc.?

**Comment by webmasterkai** [comment]
Is there protection against anon seeing it?

**Comment by bjornmeansbear** [comment]
I'll have to double check. With R&G they were discussing the option of showing SummerSale to everyone — so maybe it's the same, you can see it, but just not the price?

**Comment by webmasterkai** [comment]
It's basically a item list that can't be edited. Similar to what they want for the homepage list. We can give it a link or a checkbox or a dropdown or add it to the project list or something else...

**Comment by bjornmeansbear** [comment]
Okay.
It doesn't look like they have any items in their Summer Sale list yet anyway right? so I'll ask Esteban to get something in there so we can have a thing to look at at least... And ask him about that permissions question

**Comment by bjornmeansbear** [comment]
I got a response — only a logged in person should be able to see the summer sale after all. Anon does not get access. 

does that change the best way to show these?
