### ISSUE TITLE
Add "All fabrics are Water, Mildew and Stain Resistant" to pricelist

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#5]
That's the last bit from http://delanyandlong.com/specifications.cfm that isn't really represented...

**Comment by webmasterkai** [comment]
don't really know where to put it, but tossed in in. See Pricelist.js `lead` variable

**Comment by bjornmeansbear** [comment]
I'll figure out where to put it! Cool.
