### ISSUE TITLE
Custom PDF sys login

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/delanyandlong#74]
Customer number and zip code.
Need errors that describe the issue.
What kind of security is needed? Block after so many wrong guesses?

**Comment by bjornmeansbear** [comment]
Customer number and zip again. Check.
It would be great to have errors that at least let someone know the zip is wrong or the customer# does not exist (maybe also that zip might be a country name if not a US zip...)

I don't know about the security. I can ask DL tomorrow.

**Comment by webmasterkai** [comment]
There are other possible errors.
* User client internet connection looks faulty.
* Issue with our backend server not responding or giving internal server 500 error.
* Issue with PDF sys. Unreachable/timeout or error besides 404.

**Comment by bjornmeansbear** [comment]
Yes! great. All very helpful and hopefully would allow us to do more when I get emailed saying it doesn't work 👍

**Comment by bjornmeansbear** [comment]
Also, RG and DL are both gmail powered now, something (maybe for the future?) could be logging in w/ google account, at least for them as more of "admin" roles?
