### ISSUE TITLE
Where do we store state related to fav/project popup

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/delanyandlong#76]
Before we displayed the confirmation popup when there was an active collection item that wasn't yet `action: 'confirmed'`. That doesn't work with projects since the list item can be edited.

There needs to be some state specific to the favs/projects. It could be in the URL but I've been hating on that concept lately. I think it needs to be held in a fav/project reducer that is managed in parallel with the entity creation. Maybe something as simple as `item`, `collection` and `listItem` would be enough.

**Comment by webmasterkai** [comment]
When only 'item' is set show user all collections item is in. Allow removal from exsisting. Allow add to new collection by drop down. Allow create new collection and add to that. Allow editing details of that item within collection.

**Comment by webmasterkai** [comment]
When editing the details on a specific list item that will be set in the collection state. It will show notes field and position.

**Comment by bjornmeansbear** [comment]
I like that show what collections an item is in — we could just use an icon to do that? maybe the bookmark or a little check or just a circle ⚪  that is outlined (http://fontawesome.io/icon/circle-o/) for a collection not including that item and filled for collections including it ? ⚫  (or http://fontawesome.io/icon/circle/ or http://fontawesome.io/icon/dot-circle-o/)

**Comment by webmasterkai** [comment]
Created `cape-redux-collection`.
