### ISSUE TITLE
After login should be able to see summer sale items

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#84]
related to #16 and #41 and #27

**Comment by bjornmeansbear** [comment]
Okay, where should this go...
- Is it an option that can show up in the "Display Style?"
- Just a checkbox or button that gets added to the `pricelistHeader`?

**Comment by bjornmeansbear** [comment]
Nevermind, the display style doesn't work, it's not really a style, but another filter, or rather different content stream provider... it swaps the feed really doesn't it, so its a "switch" maybe we do a little button w/ an option or switch icon.

**Comment by bjornmeansbear** [comment]
maybe just something like this?
![screenshot 2016-10-07 14 54 05](https://cloud.githubusercontent.com/assets/324987/19201914/eef85a92-8c9d-11e6-8b1d-ed409763f798.png)

**Comment by bjornmeansbear** [comment]
Okay, so I'm more or less happy with this placement, I might tweak it design wise later, but can we now make this show only when price shows? does a button work as a think to easily show/hide and have change the data in the table?

**Comment by webmasterkai** [comment]
I'll start with a hide/show of the button based on auth status.

**Comment by bjornmeansbear** [comment]
Now we just need PDF systems to get on it! I think button is fine, and it is deinfitely turning on and off!

**Comment by bjornmeansbear** [comment]
Okay, PDF systems says this is ready, but that DL still hasn't marked anything. I'll try to get this sorted w/ Esteban and PDFsystems tomorrow...

**Comment by bjornmeansbear** [comment]
This is working now.
