### ISSUE TITLE
Show account's Showroom/Sales rep info when logged in

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#85]
Some ideas of where to put this:
- if you click the trade button (or maybe even just hover) it reveals a block w/ your rep info?
- could be added to the top of the pricelist?
- could be added at bottom of everypage when you're logged in?

**Comment by webmasterkai** [comment]
Print rgheadquarters if there is a missing showroom info.

**Comment by bjornmeansbear** [comment]
this is superseded by #102, trade button just logs you out after logged in...
