### ISSUE TITLE
They desire a message to also show up on Summer Sale

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/delanyandlong#98]
SummerSale message:
All sales are final.
All fabrics are sold as it.
No returns or exchanges.

**Comment by webmasterkai** [comment]
This is SummerSale specific text?

**Comment by bjornmeansbear** [comment]
Yes, they said this is specific to summer sale

**Comment by webmasterkai** [comment]
Is it an array of text or a single string or should we just hardcode it?

**Comment by bjornmeansbear** [comment]
I added it as an array to the default states so the line breaks could easily be kept. But it's not something they'll change much (though I have changed the r&g sale text a few times)

**Comment by bjornmeansbear** [comment]
Hard coded works
